using System.Runtime.CompilerServices;

namespace GoldSrc.HLSDK.Native;

public unsafe struct cl_enginefunc_t
{
    public delegate* unmanaged[Cdecl]<sbyte*, int> pfnSPR_Load;
    public delegate* unmanaged[Cdecl]<int, int> pfnSPR_Frames;
    public delegate* unmanaged[Cdecl]<int, int, int> pfnSPR_Height;
    public delegate* unmanaged[Cdecl]<int, int, int> pfnSPR_Width;
    public delegate* unmanaged[Cdecl]<int, int, int, int, void> pfnSPR_Set;
    public delegate* unmanaged[Cdecl]<int, int, int, wrect_t*, void> pfnSPR_Draw;
    public delegate* unmanaged[Cdecl]<int, int, int, wrect_t*, void> pfnSPR_DrawHoles;
    public delegate* unmanaged[Cdecl]<int, int, int, wrect_t*, void> pfnSPR_DrawAdditive;
    public delegate* unmanaged[Cdecl]<int, int, int, int> pfnSPR_EnableScissor;
    public delegate* unmanaged[Cdecl]<void> pfnSPR_DisableScissor;
    public delegate* unmanaged[Cdecl]<sbyte*, int*, client_sprite_t*> pfnSPR_GetList;
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int, int, void> pfnFillRGBA;
    public delegate* unmanaged[Cdecl]<SCREENINFO*, int> pfnGetScreenInfo;
    public delegate* unmanaged[Cdecl]<int, wrect_t, int, int, int, void> pfnSetCrosshair;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int, cvar_t*> pfnRegisterVariable;
    public delegate* unmanaged[Cdecl]<sbyte*, float> pfnGetCvarFloat;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*> pfnGetCvarString;
    public delegate* unmanaged[Cdecl]<sbyte*, delegate* unmanaged[Cdecl]<void>, int> pfnAddCommand;
    public delegate* unmanaged[Cdecl]<sbyte*, delegate* unmanaged[Cdecl]<byte*, int, void*, int>, int> pfnHookUserMsg;
    public delegate* unmanaged[Cdecl]<sbyte*, int> pfnServerCmd;
    public delegate* unmanaged[Cdecl]<sbyte*, int> pfnClientCmd;
    public delegate* unmanaged[Cdecl]<int, hud_player_info_t*, void> pfnGetPlayerInfo;
    public delegate* unmanaged[Cdecl]<sbyte*, float, void> pfnPlaySoundByName;
    public delegate* unmanaged[Cdecl]<int, float, void> pfnPlaySoundByIndex;
    public delegate* unmanaged[Cdecl]<float*, float*, float*, float*, void> pfnAngleVectors;
    public delegate* unmanaged[Cdecl]<sbyte*, client_textmessage_t*> pfnTextMessageGet;
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int> pfnDrawCharacter;
    public delegate* unmanaged[Cdecl]<int, int, sbyte*, int> pfnDrawConsoleString;
    public delegate* unmanaged[Cdecl]<float, float, float, void> pfnDrawSetTextColor;
    public delegate* unmanaged[Cdecl]<sbyte*, int*, int*, void> pfnDrawConsoleStringLen;
    public delegate* unmanaged[Cdecl]<sbyte*, void> pfnConsolePrint;
    public delegate* unmanaged[Cdecl]<sbyte*, void> pfnCenterPrint;
    public delegate* unmanaged[Cdecl]<int> GetWindowCenterX;
    public delegate* unmanaged[Cdecl]<int> GetWindowCenterY;
    public delegate* unmanaged[Cdecl]<float*, void> GetViewAngles;
    public delegate* unmanaged[Cdecl]<float*, void> SetViewAngles;
    public delegate* unmanaged[Cdecl]<int> GetMaxClients;
    public delegate* unmanaged[Cdecl]<sbyte*, float, void> Cvar_SetValue;
    public delegate* unmanaged[Cdecl]<int> Cmd_Argc;
    public delegate* unmanaged[Cdecl]<int, sbyte*> Cmd_Argv;
    public delegate* unmanaged[Cdecl]<sbyte*, void> Con_Printf;
    public delegate* unmanaged[Cdecl]<sbyte*, void> Con_DPrintf;
    public delegate* unmanaged[Cdecl]<int, sbyte*, void> Con_NPrintf;
    public delegate* unmanaged[Cdecl]<con_nprint_t*, sbyte*, void> Con_NXPrintf;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*> PhysInfo_ValueForKey;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*> ServerInfo_ValueForKey;
    public delegate* unmanaged[Cdecl]<float> GetClientMaxspeed;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, int> CheckParm;
    public delegate* unmanaged[Cdecl]<int, int, void> Key_Event;
    public delegate* unmanaged[Cdecl]<int*, int*, void> GetMousePosition;
    public delegate* unmanaged[Cdecl]<int> IsNoClipping;
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetLocalPlayer;
    public delegate* unmanaged[Cdecl]<cl_entity_t*> GetViewModel;
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*> GetEntityByIndex;
    public delegate* unmanaged[Cdecl]<float> GetClientTime;
    public delegate* unmanaged[Cdecl]<void> V_CalcShake;
    public delegate* unmanaged[Cdecl]<float*, float*, float, void> V_ApplyShake;
    public delegate* unmanaged[Cdecl]<float*, int*, int> PM_PointContents;
    public delegate* unmanaged[Cdecl]<float*, int> PM_WaterEntity;
    public delegate* unmanaged[Cdecl]<float*, float*, int, int, int, pmtrace_t*> PM_TraceLine;
    public delegate* unmanaged[Cdecl]<sbyte*, int*, model_t*> CL_LoadModel;
    public delegate* unmanaged[Cdecl]<int, cl_entity_t*, int> CL_CreateVisibleEntity;
    public delegate* unmanaged[Cdecl]<int, model_t*> GetSpritePointer;
    public delegate* unmanaged[Cdecl]<sbyte*, float, float*, void> pfnPlaySoundByNameAtLocation;
    public delegate* unmanaged[Cdecl]<int, sbyte*, ushort> pfnPrecacheEvent;
    public delegate* unmanaged[Cdecl]<int, edict_t*, ushort, float, float*, float*, float, float, int, int, int, int, void> pfnPlaybackEvent;
    public delegate* unmanaged[Cdecl]<int, int, void> pfnWeaponAnim;
    public delegate* unmanaged[Cdecl]<float, float, float> pfnRandomFloat;
    public delegate* unmanaged[Cdecl]<Int32, Int32, Int32> pfnRandomLong;
    public delegate* unmanaged[Cdecl]<sbyte*, delegate* unmanaged[Cdecl]<event_args_t*, void>, void> pfnHookEvent;
    public delegate* unmanaged[Cdecl]<int> Con_IsVisible;
    public delegate* unmanaged[Cdecl]<sbyte*> pfnGetGameDirectory;
    public delegate* unmanaged[Cdecl]<sbyte*, cvar_t*> pfnGetCvarPointer;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*> Key_LookupBinding;
    public delegate* unmanaged[Cdecl]<sbyte*> pfnGetLevelName;
    public delegate* unmanaged[Cdecl]<screenfade_t*, void> pfnGetScreenFade;
    public delegate* unmanaged[Cdecl]<screenfade_t*, void> pfnSetScreenFade;
    public delegate* unmanaged[Cdecl]<void*> VGui_GetPanel;
    public delegate* unmanaged[Cdecl]<int*, void> VGui_ViewportPaintBackground;
    public delegate* unmanaged[Cdecl]<sbyte*, int, int*, byte*> COM_LoadFile;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, sbyte*> COM_ParseFile;
    public delegate* unmanaged[Cdecl]<void*, void> COM_FreeFile;
    public triangleapi_t* pTriAPI;
    public efx_api_t* pEfxAPI;
    public event_api_t* pEventAPI;
    public demo_api_t* pDemoAPI;
    public net_api_t* pNetAPI;
    public IVoiceTweak* pVoiceTweak;
    public delegate* unmanaged[Cdecl]<int> IsSpectateOnly;
    public delegate* unmanaged[Cdecl]<sbyte*, nint> LoadMapSprite;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, void> COM_AddAppDirectoryToSearchPath;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int, int> COM_ExpandFilename;
    public delegate* unmanaged[Cdecl]<int, sbyte*, sbyte*> PlayerInfo_ValueForKey;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, void> PlayerInfo_SetValueForKey;
    public delegate* unmanaged[Cdecl]<int, sbyte*, int> GetPlayerUniqueID;
    public delegate* unmanaged[Cdecl]<int, int> GetTrackerIDForPlayer;
    public delegate* unmanaged[Cdecl]<int, int> GetPlayerForTrackerID;
    public delegate* unmanaged[Cdecl]<sbyte*, int> pfnServerCmdUnreliable;
    public delegate* unmanaged[Cdecl]<nint, void> pfnGetMousePos;
    public delegate* unmanaged[Cdecl]<int, int, void> pfnSetMousePos;
    public delegate* unmanaged[Cdecl]<int, void> pfnSetMouseEnable;
    public delegate* unmanaged[Cdecl]<cvar_t*> GetFirstCvarPtr;
    public delegate* unmanaged[Cdecl]<uint> GetFirstCmdFunctionHandle;
    public delegate* unmanaged[Cdecl]<uint, uint> GetNextCmdFunctionHandle;
    public delegate* unmanaged[Cdecl]<uint, sbyte*> GetCmdFunctionName;
    public delegate* unmanaged[Cdecl]<float> hudGetClientOldTime;
    public delegate* unmanaged[Cdecl]<float> hudGetServerGravityValue;
    public delegate* unmanaged[Cdecl]<int, model_t*> hudGetModelByIndex;
    public delegate* unmanaged[Cdecl]<int, void> pfnSetFilterMode;
    public delegate* unmanaged[Cdecl]<float, float, float, void> pfnSetFilterColor;
    public delegate* unmanaged[Cdecl]<float, void> pfnSetFilterBrightness;
    public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, sequenceEntry_t*> pfnSequenceGet;
    public delegate* unmanaged[Cdecl]<int, int, int, wrect_t*, int, int, int, int, void> pfnSPR_DrawGeneric;
    public delegate* unmanaged[Cdecl]<sbyte**, int*, int**, void> pfnSequencePickSentence;
    public delegate* unmanaged[Cdecl]<int*, int*, sbyte*, int*, int*, int*, void> pfnDrawString;
    public delegate* unmanaged[Cdecl]<int*, int*, sbyte*, int*, int*, int*, void> pfnDrawStringReverse;
    public delegate* unmanaged[Cdecl]<sbyte*, void> LocalPlayerInfo_ValueForKey;
    public delegate* unmanaged[Cdecl]<int*, int*, int*, uint*, void> pfnVGUI2DrawCharacter;
    public delegate* unmanaged[Cdecl]<int*, int*, int*, int*, int*, int*, uint*, void> pfnVGUI2DrawCharacterAdd;
    public delegate* unmanaged[Cdecl]<sbyte*, uint> COM_GetApproxWavePlayLength;
    public delegate* unmanaged[Cdecl]<void*> pfnGetCareerUI;
    public delegate* unmanaged[Cdecl]<void> Cvar_Set;
    public delegate* unmanaged[Cdecl]<int> pfnIsCareerMatch;
    public delegate* unmanaged[Cdecl]<sbyte*, float, int, void> pfnPlaySoundVoiceByName;
    public delegate* unmanaged[Cdecl]<sbyte*,int, void> pfnPrimeMusicStream;
    public delegate* unmanaged[Cdecl]<double> GetAbsoluteTime;
    public delegate* unmanaged[Cdecl]<int*, int, void> pfnProcessTutorMessageDecayBuffer;
    public delegate* unmanaged[Cdecl]<int*, int, void> pfnConstructTutorMessageDecayBuffer;
    public delegate* unmanaged[Cdecl]<void> pfnResetTutorMessageDecayData;
    public delegate* unmanaged[Cdecl]<sbyte*, float, int, void> pfnPlaySoundByNameAtPitch;
    public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, int, int, void> pfnFillRGBABlend;
    public delegate* unmanaged[Cdecl]<int> pfnGetAppID;
    public delegate* unmanaged[Cdecl]<cmdalias_t*> pfnGetAliasList;
    public delegate* unmanaged[Cdecl]<int*, int*, void> pfnVguiWrap2_GetMouseDelta;
}
